### ISSUE TITLE
mobile support

### ISSUE THREAD

**Issue by randydom** [chronoxor/CppServer#4]
Hello , just want to know does your framework support mobile ( iOS , Android ...etc ) or it's a Desktop specific only ?

Thank you

**Comment by chronoxor** [comment]
This framework allows to build very performance effective TCP/UDP async C++ server in a cross-platform way for major OS (Windows, Linux, OSX) in order to have a single code base. Also is allows to connect and handle lots of clients in a thread pool to share them on CPU cores. 

You can build and run CppServer for OSX and a believe it should work for iPhone as well. 

For Android using Java NIO is a way to go.

There is no need to have ultra low latency TCP server on Android or iPhone. Usually you only need a client. In most cases sync client is enough.

**Comment by randydom** [comment]
ok , an other request please if i want send a message for a specif client how it can be done , i see 

> bool TCPServer::Multicast(const void* buffer, size_t size)
But this cast a message to all connected clients , how it can be adapted to send to only one client with a specif UIID .

thanks

**Comment by randydom** [comment]
please also check your email i tried to send a message .

**Comment by chronoxor** [comment]
Please see (TCP Chat Server)[https://github.com/chronoxor/CppServer/blob/master/examples/tcp_chat_server.cpp]. You can handle client connect in ChatSession::onConnected() and put the client session into std::map<sessionId, session> protected with mutex. In ChatSession::onDisconnected() remove session from map. In this case you can send message to particular client by id any time you want.

**Comment by randydom** [comment]
please check your email ... thank you

**Comment by chronoxor** [comment]
See my commit - https://github.com/chronoxor/CppServer/commit/7aaef51c0f0186dfb42f3add8e0b4f0692acf6aa

Now you can use FindSession() method to send data to the required session:

auto session = server.FindSession(id);
if (session)
    session->Send(buffer, size);

**Comment by randydom** [comment]
Thank you
